name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      # Add this step to debug npm version
      - name: Debug environment
        run: |
          node --version
          npm --version
          ls -la
          ls -la src/assets/img || echo "No images directory found"
      
      # Create assets directory if it doesn't exist
      - name: Ensure assets directory exists
        run: |
          mkdir -p src/assets/img
          touch src/assets/img/.gitkeep
      
      # Use npm install instead of npm ci for more flexibility
      - name: Install dependencies
        run: npm install
      
      # Add this step to debug build issues
      - name: List files before build
        run: ls -la
      
      - name: Build
        run: npm run build
      
      # Add this step to debug build output
      - name: List build output
        run: |
          ls -la dist
          ls -la dist/assets || echo "No assets directory in dist"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 